server:
  port: 8083
spring:
  application:
    name: provider-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/USER1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  redis:
    port: 6379
    host: 192.168.44.128
  rabbitmq:
    host: 192.168.44.128
    port: 5672
    username: admin
    password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/,http://localhost1:8082/eureka/
es.host: 192.168.44.128
es.post: 9300