server:
  port: 8082
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost1
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka/
